export const items = [
  {
    id: Math.random(),
    title: "وجبه فطار",
    des: "وصف الفطار",
    price: "100 جنيه",
    category: "فطار",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه غدا",
    des: "وصف الفطار",
    price: "80 جنيه",
    category: "غدا",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    des: "وصف الفطار",
    price: "40 جنيه",
    category: "عشاء",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه غدا ممتاز",
    des: "وصف الفطار",
    price: "30 جنيه",
    category: "غدا",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه عشاء درجه اولى",
    des: "وصف الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه فطار",
    des: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: require("../src/components/img/download (1).png"),
  },
  {
    id: Math.random(),
    title: "وجبه سناك",
    des: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: require("../src/components/img/download (1).png"),
  },
];
